# Generated by Django 4.2.3 on 2023-07-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'avisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('feliz', models.TextField(blank=True, db_column='Feliz', null=True)),
                ('cansado', models.TextField(blank=True, db_column='Cansado', null=True)),
                ('concentrado', models.TextField(blank=True, db_column='Concentrado', null=True)),
                ('pensativo', models.TextField(blank=True, db_column='Pensativo', null=True)),
                ('serio', models.TextField(blank=True, db_column='Serio', null=True)),
            ],
            options={
                'db_table': 'emoji',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipeCipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('setor', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'equipe_cipa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventosAu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(blank=True, max_length=5, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventos_au',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventosGe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(blank=True, max_length=5, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventos_ge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=30)),
                ('senha', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerguntasF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=20, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perguntas_f',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusAtendimento',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=20)),
                ('status_agora', models.CharField(blank=True, max_length=15, null=True)),
                ('unidade', models.CharField(blank=True, max_length=15, null=True)),
                ('local_ss', models.CharField(blank=True, max_length=15, null=True)),
                ('humor', models.CharField(blank=True, max_length=15, null=True)),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'status_atendimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusAtendimentoT',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=20)),
                ('status_agora', models.CharField(blank=True, max_length=15, null=True)),
                ('unidade', models.CharField(blank=True, max_length=15, null=True)),
                ('local_ss', models.CharField(blank=True, max_length=15, null=True)),
                ('humor', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'status_atendimento_t',
                'managed': False,
            },
        ),
    ]
